import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.box}>
          <h6 className={styles.header}>Which of the below statements about electricity is not true ?</h6>
          <div className={styles.questions}>
            {/* <p>Electricity is measured in units called watts</p> */}
            <label className={styles.radioContainer}>Electricity is measured in units called watts
              <input type="radio" name="radio" value="question-one" disabled/>
              <span className={styles.checkmark}></span>
            </label>
          </div>
          <div className={styles.questions}>
            {/* <p>Electricity flows at the speed of light</p> */}
            <label className={styles.radioContainer}>Electricity flows at the speed of light
              <input type="radio" name="radio" value="question-one" disabled/>
              <span className={styles.checkmark}></span>
            </label>
          </div>
          <div className={styles.questions}>
            {/* <p>Electricity is a primary energy source</p> */}
            <label className={styles.radioContainer}>Electricity is a primary energy source
              <input type="radio" checked="checked" name="radio" value="question-one" disabled/>
              <span className={styles.checkmark}></span>
            </label>
          </div>
        </div>
      </main>
    </div>
  )
}
